
" ===== OS/SOFTWARE/PLUGINS =====
"
set clipboard+=unnamedplus      "enable nvim to use clipboard

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'lifepillar/vim-solarized8'
Plugin 'junegunn/fzf.vim'
Plugin 'preservim/nerdtree'
call vundle#end()

if filereadable("/usr/share/doc/fzf/examples/fzf.vim")
	"Ubuntu loads fzf from here, seems to work without this on Arch
	source /usr/share/doc/fzf/examples/fzf.vim
endif

" ===== TEXT =====
"
set noexpandtab                 "use tabs
set smarttab                    "also remove a whole tab (worth of spaces) when BS pressed once
set tabstop=8                   "number of spaces to display for a tab char
set shiftwidth=8                "number of spaces to insert on auto indent

" ===== BUFFERS =====
"
set autowriteall		"auto save buffers
set nostartofline               "don't jump to the start of line when switching buffers
set undodir=~/.local/share/nvim/undos/
set undofile			"store undo history to a file so its not ~undone~ on buffer save

" ===== DISPLAY =====
"

" Enable true color 启用终端24位色
" Required for tmux, taken from https://github.com/tmux/tmux/issues/1246
if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

syntax on
set background=dark
colorscheme solarized8_high
set number                      "line numbering
set norelativenumber		"relative numbering off
set hlsearch                    "search highlighting on
set nolist                      "don't display whitespace by default, listchars displays pretty much everything
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
"set spell                       "turn on spell checking - why not?
set splitbelow splitright       "new splits open below, right
set cursorline			"highlight the current line

let g:airline#extensions#tabline#enabled = 1

" ===== SEARCH =====
"
set gdefault                    "by default, replace all instances of a substitution
set noignorecase                "case sensitive by default

" ===== FILES =====
"
set wildmode=longest,list,full  "make file opening similar to the shell
set wildmenu

" ===== COMPLETION =====
"
set completeopt=menu,preview,longest

" ===== MOVEMENT and MAPPINGS =====
"
set scroll=5                    "the number of lines to scroll with ctrl-U/ctrl-D
set scrolloff=6                 "sets the number of lines that must be on-screen
                                "fuzzy finder
nmap <C-f> :FZF<CR>
nmap <C-b> :Buffers<CR>
                                "shortcut for saving files
nnoremap <leader>w :w<cr>
                                "close the current buffer without losing window split
map <leader>bd :bp\|bd #<CR>
nmap <C-x> :bp\|bd #<CR>
nnoremap <leader>ld :ls<CR>:bd<space>
                                "shift + movement keys, scroll buffer up and
                                "down, and cycle buffers
map <S-j> j<C-e>
map <S-k> k<C-y>
map <S-h> :bprevious<CR>
map <S-l> :bnext<CR>

noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-h> <C-w>h
noremap <C-l> <C-w>l
                                " Make adjusing split sizes a bit more friendly
noremap <C-Left> :vertical resize -3<CR>
noremap <C-Right> :vertical resize +3<CR>
noremap <C-Up> :resize +3<CR>
noremap <C-Down> :resize -3<CR>

